name: biblioteca_musica
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_nsd: ^1.3.2
  file_picker: 5.2.4
  drift: 
  sqlite3_flutter_libs: 
  path_provider: 
  path: 
  provider: 
  drift_db_viewer: 
  dotted_border: 
  multicast_dns: ^0.3.2+3
  
  mp3_info: 
  audioplayers:
  tuple: ^2.0.1
  dio: ^5.2.1+1
  shared_preferences: ^2.1.2
  nsd: ^2.3.1
  bitsdojo_window: ^0.1.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/recursos/
