name: biblioteca_musica
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: 5.2.4
  drift: 
  sqlite3_flutter_libs: 
  path_provider: 
  path: 
  provider: 
  drift_db_viewer: 
  dotted_border: 
  
  mp3_info: 
  audioplayers:
  tuple: ^2.0.1
  dio: ^5.2.1+1
  shared_preferences: ^2.1.2
  bitsdojo_window: ^0.1.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  rxdart: ^0.27.7
  bloc_concurrency: ^0.2.2
  file_selector: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  drift_dev: ^2.11.1
  build_runner: ^2.4.6
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/recursos/


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/recursos/kopi_icono.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/recursos/kopi_icono.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/recursos/kopi_icono.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/recursos/kopi_icono.png"